export { default as About } from './screens/About/About.js'
export { default as FAQ } from './screens/FAQ/FAQ.js'
export { default as OurTeam } from './screens/OurTeam/OurTeam.js'
export { default as Publications } from './screens/Publications/Publications.js'
export { default as Resources } from './screens/Resources/Resources.js'
