services:
  root:
    image: front-end-monorepo_dev:latest
    environment:
      PANOPTES_ENV: staging
      APP_ENV: development
    build:
      context: ../../
      target: builder
      args:
        - NEXT_TELEMETRY_DISABLED=1
        - APP_ENV=development
    entrypoint:
      - "pnpm"
      - "--filter"
      - "@zooniverse/fe-root"
    command: ["dev"]
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/packages/app-root/src
