version: '3.7'

services:
  root:
    image: front-end-monorepo_dev:latest
    build:
      context: ../../
    entrypoint:
      - "yarn"
      - "workspace"
      - "@zooniverse/fe-root"
    command: ["dev"]
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/packages/app-root/src
